#!/usr/bin/env bash
# Regenerates manifest.json's digests from the fixture files actually
# present in this directory. Run this in the same commit as any content
# change to any of the fixture files listed below.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

bucketing_digest="$(sha256sum bucketing-vectors.json | awk '{print $1}')"
rollout_digest="$(sha256sum rollout-outcome-vectors.json | awk '{print $1}')"
targeting_model_digest="$(sha256sum targeting-model-vectors.json | awk '{print $1}')"
targeting_model_refusals_digest="$(sha256sum targeting-model-authoring-refusals.json | awk '{print $1}')"

cat > manifest.json << MANIFEST
{
  "\$comment": "SHA-256 digests of the fixture files in this repository, regenerated by scripts/update-manifest.sh whenever any of them changes. A client repository's drift check fetches this file (or the fixture files directly) over HTTPS and compares against its own local copy; a mismatch here without a matching content update is itself a sign something was edited by hand instead of through the sync script.",
  "files": {
    "bucketing-vectors.json": "$bucketing_digest",
    "rollout-outcome-vectors.json": "$rollout_digest",
    "targeting-model-vectors.json": "$targeting_model_digest",
    "targeting-model-authoring-refusals.json": "$targeting_model_refusals_digest"
  }
}
MANIFEST

echo "manifest.json regenerated:"
cat manifest.json
